### ISSUE TITLE
java.lang.RuntimeException: view must have a tag

### ISSUE THREAD

**Issue by yangdong125845** [liangjingkanji/BRV#125]
## 问题描述

java.lang.RuntimeException: view must have a tag
        at com.hibobi.store.DataBinderMapperImpl.getDataBinder(DataBinderMapperImpl.java:2623)
        at androidx.databinding.MergedDataBinderMapper.getDataBinder(MergedDataBinderMapper.java:74)
        at androidx.databinding.DataBindingUtil.bind(DataBindingUtil.java:199)
        at androidx.databinding.ViewDataBinding.bind(ViewDataBinding.java:695)
        at com.hibobi.store.databinding.ItemInvalidCouponBinding.bind(ItemInvalidCouponBinding.java:94)
        at com.hibobi.store.databinding.ItemInvalidCouponBinding.bind(ItemInvalidCouponBinding.java:82)

## 版本
- BRV: 1.3.53
- Gradle:  
- Android Studio:  
- Android:

**Comment by liangjingkanji** [comment]
我没看到任何和本框架相关的错误信息
建议尝试谷歌搜索和定位下源码位置

**Comment by liangjingkanji** [comment]
1. 建议尝试clean project然后重新编译运行
2. 重命名布局文件后重新编译运行
