### ISSUE TITLE
分组嵌套极快速展开收缩后闪退 IndexOutOfBoundsException

### ISSUE THREAD

**Issue by 404N** [liangjingkanji/BRV#131]
## 如何复现
建议步骤:
运行demo->选择分组->嵌套分组->快速点击展开和收缩一级分组和二级分组

## 截图
AndroidRuntime: FATAL EXCEPTION: main
    Process: com.drake.brv.sample, PID: 18997
    java.lang.IndexOutOfBoundsException: Index: 11, Size: 9
        at java.util.ArrayList.addAll(ArrayList.java:613)
        at com.drake.brv.BindingAdapter$BindingViewHolder.expand(BindingAdapter.kt:1138)
        at com.drake.brv.BindingAdapter$BindingViewHolder.expandOrCollapse(BindingAdapter.kt:1199)
        at com.drake.brv.BindingAdapter$BindingViewHolder.expandOrCollapse$default(BindingAdapter.kt:1196)
        at com.drake.brv.sample.ui.fragment.group.GroupFragment$initView$1$1.invoke(GroupFragment.kt:44)
        at com.drake.brv.sample.ui.fragment.group.GroupFragment$initView$1$1.invoke(GroupFragment.kt:39)
        at com.drake.brv.BindingAdapter$BindingViewHolder._init_$lambda-0(BindingAdapter.kt:1041)
        at com.drake.brv.BindingAdapter$BindingViewHolder.lambda$G0-koxWsBW5vLPI8vtlQiQjT9jM(Unknown Source:0)
        at com.drake.brv.-$$Lambda$BindingAdapter$BindingViewHolder$G0-koxWsBW5vLPI8vtlQiQjT9jM.onClick(Unknown Source:6)
        at android.view.View.performClick(View.java:7201)
        at android.view.View.performClickInternal(View.java:7170)
        at android.view.View.access$3500(View.java:806)
        at android.view.View$PerformClick.run(View.java:27562)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7697)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

## 版本
- BRV:master分支
- Gradle: 
- Android Studio:  2020.3.1
- Android:

**Comment by liangjingkanji** [comment]
我快速点击也无法复现该问题

https://user-images.githubusercontent.com/21078112/158731611-9ebe915a-1554-42cf-87b0-e143e1782e77.mp4


请备注版本号或者提交commit, 而不是分支名称

**Comment by 404N** [comment]
> 

https://user-images.githubusercontent.com/30525962/158745835-c38a8aff-9ed5-44cd-bfd2-29fdc69b26aa.mp4

**Comment by 404N** [comment]
https://user-images.githubusercontent.com/30525962/158746329-5440c7ed-c536-408f-9b7c-bf4950a9eafb.mp4

不知道你能不能看得到，不知道为什么我这边传视频是黑屏

**Comment by liangjingkanji** [comment]
> Screenrecorder.mp4 
> 不知道你能不能看得到，不知道为什么我这边传视频是黑屏

看不到, 你复制视频文件直接在剪贴板粘贴就行了/  如果还无法复现我建议你自己尝试修复

**Comment by 404N** [comment]
https://user-images.githubusercontent.com/30525962/158748331-1adfb08c-3a91-4796-9059-1215994d45d1.mp4

这回可以了

**Comment by liangjingkanji** [comment]
没你手速快复现不出来

**Comment by 404N** [comment]
好吧，这个我在brvah那个库也遇到了同款问题，我研究一下吧

**Comment by liangjingkanji** [comment]
@404N 欢迎共同修复此问题

**Comment by liangjingkanji** [comment]
你可以将展开折叠动画关闭尝试能否继续复现问题吗?

```kotlin
rv.setup{
    expandAnimationEnabled = false
    // ....
}
```

**Comment by LeonShannon** [comment]
我有类似的问题，不知道对于问题的解决有没有帮助。我加上圈住的代码，就会出现类似的数组越界
<img width="762" alt="image" src="https://user-images.githubusercontent.com/24221796/159403719-aab31831-9620-4f94-87ff-8430fdc299e2.png">

**Comment by liangjingkanji** [comment]
因为展开和折叠会导致position变化, 你的modelPosition此时已经过时
关于展开和折叠的监听请使用`onExpand`来监听

**Comment by LeonShannon** [comment]
> 

是的。只用expandOrCollapse()就完全可以实现

**Comment by liangjingkanji** [comment]
@LeonShannon 

和你这个问题不同, 你这个是必现, 他提出的是快速情况下偶现

**Comment by 404N** [comment]
> 你可以将展开折叠动画关闭尝试能否继续复现问题吗?
> 
> ```kotlin
> rv.setup{
>     expandAnimationEnabled = false
>     // ....
> }
> ```
> 
> > 因为我没有你这个单身30年的手速无法复现

关闭动画确实不会出现闪退了，但是分组出现错误了

https://user-images.githubusercontent.com/30525962/159415388-59fda980-6ef6-4f05-a172-2dcf0ed9efb8.mp4

**Comment by liangjingkanji** [comment]
问题待解决, 你可以通过将`onFastClick`改为`onClick`开启点击防抖动临时解决此问题

**Comment by boboqun** [comment]
有可能是add对象时添加了相同的对象导致处理错乱

**Comment by liangjingkanji** [comment]
> 有可能是add对象时添加了相同的对象导致处理错乱

这个是快速点击才能复现, 也没有添加相同对象.  不过欢迎你PR

**Comment by liangjingkanji** [comment]
> 问题待解决, 你可以通过将`onFastClick`改为`onClick`开启点击防抖动临时解决此问题

这种快速点击出现的数据错乱问题暂时没有好的解决办法, 建议采取此方式解决
