### ISSUE TITLE
RecyclerView刷新数据不同步导致的异常崩溃

### ISSUE THREAD

**Issue by LeonShannon** [liangjingkanji/BRV#136]
## 如何复现
建议步骤:
-  是否可以在Sample复现 
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图

异常堆栈信息或者手机截图/视频
Thread Name: 'main'
Back traces starts.
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionBindingViewHolder{88cd685 position=10 id=-1, oldPos=9, pLpos:9 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{fc962a7 VFED..... ......I. 0,0-196,2256 #7f090561 app:id/rvMyGroup}, adapter:com.drake.brv.BindingAdapter@ca3d1fa, layout:com.drake.brv.layoutmanager.HoverLinearLayoutManager@d16c3ab, context:com.vgjump.jump.ui.main.MainActivity@a3983fd
	at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:6156)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6339)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
	at com.drake.brv.layoutmanager.HoverLinearLayoutManager.onLayoutChildren(HoverLinearLayoutManager.java:207)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4255)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4010)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
	at android.view.View.layout(View.java:23211)
	at android.view.ViewGroup.layout(ViewGroup.java:6451)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
	at android.view.View.layout(View.java:23211)
	at android.view.ViewGroup.layout(ViewGroup.java:6451)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23211)
	at android.view.ViewGroup.layout(ViewGroup.java:6451)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
	at android.view.View.layout(View.java:23211)
	at android.view.ViewGroup.layout(ViewGroup.java:6451)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1263)
	at android.view.View.layout(View.java:23211)
	at android.view.ViewGroup.layout(ViewGroup.java:6451)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23211)
	at android.view.ViewGroup.layout(ViewGroup.java:6451)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23211)
	at android.view.ViewGroup.layout(ViewGroup.java:6451)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23211)
	at android.view.ViewGroup.layout(ViewGroup.java:6451)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at android.view.View.layout(View.java:23211)
	at android.view.ViewGroup.layout(ViewGroup.java:6451)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:963)
	at android.view.View.layout(View.java:23211)
	at android.view.ViewGroup.layout(ViewGroup.java:6451)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3850)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3311)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2236)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8772)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1031)
	at android.view.Choreographer.doCallbacks(Choreographer.java:849)
	at android.view.Choreographer.doFrame(Choreographer.java:779)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1016)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:257)
	at android.app.ActivityThread.main(ActivityThread.java:8215)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:626)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1031)
Back traces ends.

## 版本
- BRV:1.3.56
- Gradle: 7.1.2
- Android Studio:  Android Studio Bumblebee | 2021.1.1 Patch 2 Build #AI-211.7628.21.2111.8193401,
- Android:Android 11 型号：Vivo V1955A

**Comment by LeonShannon** [comment]
问题是，add数据的时候会出现这样的问题。按照网上的方法捕获了下异常，可以暂时解决这个问题
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/24221796/160352766-ffd6262b-432e-4bfb-8eee-c124aa1fb2a0.png">
参考链接：https://juejin.cn/post/6844903568080633870#heading-1

**Comment by LeonShannon** [comment]
我找到问题了。mutable add数据之后应该notifyDataSetChanged，而不是notifyItemInserted
<img width="580" alt="image" src="https://user-images.githubusercontent.com/24221796/160387461-df979a28-1bdf-404b-bc43-e76ebec50ed8.png">

**Comment by liangjingkanji** [comment]
建议你用models而不是`_data`, 除非你要为models赋值但是不希望刷新数据才使用_data, 因为models赋值会自动`notifyDataChaned()`

**Comment by LeonShannon** [comment]
> models

但是我想要插入到指定位置，是不是就只能只有使用呢？

**Comment by liangjingkanji** [comment]
无论你插入多少数据什么位置数据都可以使用`notifyDataChaned ()`, 这是全部更新的意思

另外你的异常肯定是使用`notifyItemInserted()`错误的问题, 并不是不允许使用该方法
