### ISSUE TITLE
Inconsistency detected

### ISSUE THREAD

**Issue by daiwenbo88** [liangjingkanji/BRV#165]
## 问题描述
Inconsistency detected. Invalid view holder adapter positionBindingViewHolder
## 如何复现
1. 主界面通过 show()和 hide() 来切换Fragment  
2. 界面渲染出来后 按下手机电源键 关闭屏幕
3. 再次打开屏幕 回到App界面就崩溃

4. 列表界面使用 PageRefreshLayout 包裹 RecyclerView
5. 数据加载代码如下
```
     lifecycleScope.launch {
            mViewModel.feedStateFlow
                .flowWithLifecycle(lifecycle,Lifecycle.State.STARTED)
                .collect {
                    LogUtils.d(TAG, "initData: ${it.size}")
                    //第二点亮开屏幕  回到app界面 会收到StateFlow 发射过来的数据 就导致崩溃了
                    binding.refreshLayout.addData(it, binding.recyclerView.bindingAdapter,hasMore = {false})
                }
        }
````

建议步骤:
-  是否可以在Sample复现
- 如果不能在Sample复现建议Fork本仓库然后复现
- 主要代码

## 截图
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionBindingViewHolder{19967b2 position=28 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{4d1d431 VFED..... ......ID 0,0-1080,1804 #7f0801c3 app:id/recyclerView}, adapter:com.drake.brv.BindingAdapter@ae47716, layout:com.drake.brv.layoutmanager.HoverStaggeredGridLayoutManager@939897, context:com.xx.xx.MainActivity@ccb0bf5
        at androidx.recyclerview.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:6156)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6339)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
        at androidx.recyclerview.widget.LayoutState.next(LayoutState.java:98)
        at androidx.recyclerview.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1581)
        at androidx.recyclerview.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:691)
        at androidx.recyclerview.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:604)
        at com.drake.brv.layoutmanager.HoverStaggeredGridLayoutManager.onLayoutChildren(HoverStaggeredGridLayoutManager.java:189)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:4255)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4010)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4578)
        at android.view.View.layout(View.java:22190)
        at android.view.ViewGroup.layout(ViewGroup.java:6372)
        at com.scwang.smart.refresh.layout.SmartRefreshLayout.onLayout(SmartRefreshLayout.java:651)
        at android.view.View.layout(View.java:22190)
        at android.view.ViewGroup.layout(ViewGroup.java:6372)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22190)
        at android.view.ViewGroup.layout(ViewGroup.java:6372)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
        at android.view.View.layout(View.java:22190)
        at android.view.ViewGroup.layout(ViewGroup.java:6372)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22190)
        at android.view.ViewGroup.layout(ViewGroup.java:6372)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
        at android.view.View.layout(View.java:22190)
        at android.view.ViewGroup.layout(ViewGroup.java:6372)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22190)
        at android.view.ViewGroup.layout(ViewGroup.java:6372)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1845)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22190)
        at android.view.ViewGroup.layout(ViewGroup.java:6372)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
        at android.view.View.layout(View.java:22190)
        at android.view.ViewGroup.layout(ViewGroup.java:6372)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1845)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
        at android.view.View.layout(View.java:22190)
        at android.view.ViewGroup.layout(ViewGroup.java:6372)

## 版本
- BRV: `1.3.63`
- Gradle: `7.2`
- Android Studio:  `Bumblebee | 2021.1.1 Path 2`
- Android:`OPPO R17` Android 10

**Comment by liangjingkanji** [comment]
`PageRefreshLayout.addData`是会根据下拉刷新状态去决定是否添加数据, 请不要直接使用

你可以使用`bindingAdapyer.addModel()`去添加数据

**Comment by liangjingkanji** [comment]
不过我查看addData方法也不应该导致崩溃, 我估计是你通过异步线程addData导致的问题, 

具体建议你搜索此异常或者查看这篇文章: [当RecyclerView遇到Inconsistency detected崩溃时
](https://www.jianshu.com/p/2eca433869e9)

**Comment by daiwenbo88** [comment]
经过不断测试发现是由于 StateFlow 数据倒灌导致的崩溃 
同时在测试中 发现以下2个监听函数 上拉加载 和下拉刷新 每次关闭屏幕 在点开屏后 都会有一个自动执行
不知道是不是我用的不对

```
        binding.refreshLayout.onRefresh {  
            LogUtils.d(TAG, "initData: 刷新数据")    
        }

        binding.refreshLayout.onLoadMore {
            LogUtils.d(TAG, "initData: 加载数据")
        }
```

**Comment by liangjingkanji** [comment]
你在demo复现给我看下, 这个应该和你调用刷新的位置有关

**Comment by liangjingkanji** [comment]
我作为作者由衷希望快速给你解决问题, 但是你的回答速度不尽如人意

**Comment by daiwenbo88** [comment]
东哥大佬很抱歉以为你今天在休息呢 工作任务太重没能及时回复到您 我明天fork 代码 把Demo 写出来看看

**Comment by liangjingkanji** [comment]
我, 活在互联网

**Comment by daiwenbo88** [comment]
demo 代码已经提交 东哥早点休息

**Comment by liangjingkanji** [comment]
我们只是排查复现问题, fork仓库就够了你创建pr干什么

**Comment by liangjingkanji** [comment]
从你的demo我只发现了`stateFlow: `会在屏幕熄灭点亮反复执行, 但是这不在`onRefresh/onLoadMore`回调中

**Comment by liangjingkanji** [comment]
长时间没有回复我将关闭问题
