### ISSUE TITLE
不使用DataBinding会直接崩溃

### ISSUE THREAD

**Issue by br3ant** [liangjingkanji/BRV#17]
version:1.3.13 

java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/databinding/DataBinderMapperImpl;
        at androidx.databinding.DataBindingUtil.<clinit>(DataBindingUtil.java:32)
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:95)
        at com.drake.brv.BindingAdapter.onCreateViewHolder(BindingAdapter.kt:127)
        at com.drake.brv.BindingAdapter.onCreateViewHolder(BindingAdapter.kt:67)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1627)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)

**Comment by liangjingkanji** [comment]
这个问题无法解决因为已经使用到了其导包. 你可以不使用DataBinding但是也要打开其开关 
(现在DataBinding属于官方唯一推荐)

```groovy
android {
    //... 即使你不使用DataBinding也要打开其开关
    buildFeatures.dataBinding = true
}

dependencies {
    //...
    implementation 'com.github.liangjingkanji:BRV:1.3.22'
}
```
