### ISSUE TITLE
ClassCastException: kotlin.collections.EmptyList cannot be cast to kotlin.collections.MutableList

### ISSUE THREAD

**Issue by wenge1215** [liangjingkanji/BRV#2]
手机型号：小米6
Android：9
操作：头|脚布局-----> 添加头部

2020-05-23 11:08:47.112 27889-27889/com.drake.brv.sample E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.drake.brv.sample, PID: 27889
    java.lang.ClassCastException: kotlin.collections.EmptyList cannot be cast to kotlin.collections.MutableList
        at com.drake.brv.BindingAdapter.addHeader(BindingAdapter.kt:300)
        at com.drake.brv.BindingAdapter.addHeader$default(BindingAdapter.kt:297)
        at com.drake.brv.sample.ui.fragment.HeaderFooterFragment$initToolbar$1.onMenuItemClick(HeaderFooterFragment.kt:74)
        at androidx.appcompat.widget.Toolbar$1.onMenuItemClick(Toolbar.java:207)
        at androidx.appcompat.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:781)
        at androidx.appcompat.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:840)
        at androidx.appcompat.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:158)
        at androidx.appcompat.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:991)
        at androidx.appcompat.view.menu.MenuPopup.onItemClick(MenuPopup.java:128)
        at android.widget.AdapterView.performItemClick(AdapterView.java:318)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1198)
        at android.widget.AbsListView$PerformClick.run(AbsListView.java:3178)
        at android.widget.AbsListView$3.run(AbsListView.java:4132)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6878)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)

**Comment by liangjingkanji** [comment]
好的, 稍后更新

**Comment by liangjingkanji** [comment]
升级到1.2.14即可, 增加分组和悬停以及强大的分割线功能
