### ISSUE TITLE
[FR] 缺少 `android.permission.ACCESS_NETWORK_STATE` 权限导致的崩溃

### ISSUE THREAD

**Issue by zhaobozhen** [liangjingkanji/BRV#203]
## 问题描述
我的应用没有联网权限，因此我 remove 掉了 `android.permission.ACCESS_NETWORK_STATE` 权限。但是发现引起了崩溃。应该可以在 `isNetworking` 方法内判断下是否拥有该权限。

### 期望行为
不声明 `android.permission.ACCESS_NETWORK_STATE` 权限也可正常使用。

## 如何复现

> fork仓库并复现问题可以快速解决, 猜测只会让问题晦涩难懂, 耽误所有人时间

## 截图

```
Caused by: java.lang.SecurityException: ConnectivityService: Neither user 10766 nor current process has android.permission.ACCESS_NETWORK_STATE.
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at android.net.IConnectivityManager$Stub$Proxy.getActiveNetwork(IConnectivityManager.java:1562)
        at android.net.ConnectivityManager.getActiveNetwork(ConnectivityManager.java:1175)
        at com.drake.statelayout.StateLayout.isNetworking(StateLayout.kt:374)
        at com.drake.statelayout.StateLayout.showLoading(StateLayout.kt:217)
        at com.drake.statelayout.StateLayout.showLoading$default(StateLayout.kt:203)
        at com.absinthe.littleprocessy.MainActivity.initView(MainActivity.kt:263)
        at com.absinthe.littleprocessy.MainActivity.onCreate(MainActivity.kt:68)
        at android.app.Activity.performCreate(Activity.java:8281)
        at android.app.Activity.performCreate(Activity.java:8245)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
```

**Comment by liangjingkanji** [comment]
这个问题发生在缺省页依赖[StateLayout](https://github.com/liangjingkanji/StateLayout)中, 我紧急修复下

**Comment by liangjingkanji** [comment]
我修改标签为提议, 因为这不属于自带bug

我在考虑是否需要直接删除`ACCESS_NETWORK_STATE`权限, 但是这样开发者可能不会主动添加权限, 你觉得如何选择

**Comment by zhaobozhen** [comment]
我觉得不删除也可以，现在很少有应用不声明联网权限。如果开发者有特殊需求就自己 remove 掉。

**Comment by liangjingkanji** [comment]
有道理不愧是你

**Comment by liangjingkanji** [comment]
但是我发现我不声明权限依然无法复现崩溃问题, 你能否fork仓库复现问题

**Comment by liangjingkanji** [comment]
请升级版本至`1.3.77`
