### ISSUE TITLE
刷新数据时偶现 BindingAdapter 提示 NullPointerException

### ISSUE THREAD

**Issue by syxc** [liangjingkanji/BRV#204]
## 刷新数据时偶现 BindingAdapter 提示 NullPointerException

异常堆栈信息如下：

```java
E/AndroidRuntime: FATAL EXCEPTION: main

java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
at com.drake.brv.BindingAdapter.getItemViewType(BindingAdapter.kt:194)
at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6367)
at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6300)
at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6296)
at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2330)
at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1631)
at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1591)
at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:668)
at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4309)
at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4012)
```

## 版本
- BRV: 1.3.69
- Android: 鸿蒙 2.0，华为 P20 手机
- Gradle: 7.2
- Android Studio: Chipmunk | 2021.2.1 Patch 1

**Comment by liangjingkanji** [comment]
我看异常问题的确是存在取数据然后`getClass`导致的空指针, 建议你排查下或者能fork仓库复现问题, 否则我将无法解决

**Comment by syxc** [comment]
> 我看异常问题的确是存在取数据然后`getClass`导致的空指针, 建议你排查下或者能fork仓库复现问题, 否则我将无法解决
> 
> 复现问题是我的第一步

好的，我按你提示的仔细排查，针对做些处理，若有复现，我再来反馈。

**Comment by liangjingkanji** [comment]
排查到没? 

> 怎么在我这每次都是我催着开发者快解决问题, 经常遇到不回复或者回复很慢的...

**Comment by syxc** [comment]
> 排查到没? 
> 
> > 怎么在我这每次都是我催着开发者快解决问题, 经常遇到不回复或者回复很慢的...

数据空字段做了处理，此问题暂时没能复现，issue 先关了吧，重现了我会反馈的，多谢了。

**Comment by liangjingkanji** [comment]
没事, 我只是不想因为bug耽误大家工作进度, 也是欢迎自己能排查问题并解决的, 这是一个属于社区的开源项目
