### ISSUE TITLE
 addType<Int>报错

### ISSUE THREAD

**Issue by 1Ezreal** [liangjingkanji/BRV#377]
## 问题描述
   addType<Int>(R.layout.item_integral_sign)
Int类型报错，改为String/Integer类型正常
### 期望行为
正常
## 如何复现

> 任何业务相关问题没有fork仓库复现问题一律无法解决, 凭空猜测只会让问题晦涩难懂, 大量耽误项目维护时间

## 截图

异常堆栈信息或者手机截图/视频(拖拽到输入框即可上传)
   android.util.NoSuchPropertyException: Please add item model type : addType<java.lang.Integer>(R.layout.item)
                 	at com.drake.brv.BindingAdapter.getItemViewType(BindingAdapter.kt:197)
                 	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6608)
## 版本
- BRV:1.4.2
- Android:9
- Gradle: 7.4.2
- Android Studio:2022.2.1 Patch 2

**Comment by liangjingkanji** [comment]
这个错误是`addType`的泛型和models里面的元素类型对应不上, 我不知道你集合里面是否添加`Integer`(Kotlin里面不存在这个类型)

如果还有问题请fork仓库复现此问题发给我链接

**Comment by 1Ezreal** [comment]
1.4.0并不会出现这个问题，我写个demo试试是否是项目问题导致

**Comment by 1Ezreal** [comment]
改了Sample中 SimpleFragment的
addType<SimpleModel>->addType<Int>
直接报错
  android.util.NoSuchPropertyException: Please add item model type : addType<java.lang.Integer>(R.layout.item)
                                                                                                    	at com.drake.brv.BindingAdapter.getItemViewType(BindingAdapter.kt:197)
                                                                                                    	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6367)

**Comment by 1Ezreal** [comment]
![image](https://github.com/liangjingkanji/BRV/assets/25078212/0d383ad9-c1bd-4eb3-b4f9-bf5ccdc4735e)
![image](https://github.com/liangjingkanji/BRV/assets/25078212/4a9f3585-5606-4db1-9712-1f5ccef3ff24)

**Comment by liangjingkanji** [comment]
的确存在这个问题, 和我为了适配集合泛型多类型需求有关, 该问题会在近期修复

**Comment by liangjingkanji** [comment]
你应该知道该bug已经早就被修复了吧

**Comment by 1Ezreal** [comment]
看到更新了0.0
